/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mini_robot.glb --output src/components/canvas/MiniRobot.tsx --types --shadows 
Author: YarikLegendary (https://sketchfab.com/YarikLegendary)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mini-robot-cf5dd6fed1f14e33aaa396c558d3c747
Title: Mini robot
*/

import * as THREE from 'three'
import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
  }
  materials: {
    Acetal_Resin_White_2: THREE.MeshStandardMaterial
    ['Aluminum_-_Anodized_Glossy_Grey']: THREE.MeshStandardMaterial
    ABS_White: THREE.MeshStandardMaterial
    Acetal_Resin_White: THREE.MeshStandardMaterial
    Acetal_Resin_White_1: THREE.MeshStandardMaterial
    ['Aluminum_-_Anodized_Rough_Grey']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

interface MiniRobotProps extends JSX.IntrinsicElements['group'] {
  isListening?: boolean;
  isSpeaking?: boolean;
}

export function MiniRobot({ isListening = false, isSpeaking = false, ...props }: MiniRobotProps) {
  const groupRef = useRef<THREE.Group>(null)
  const headRef = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/mini_robot.glb') as GLTFResult
  
  // Animation state
  const idleRotation = useRef(0)
  const speakAnimation = useRef(0)
  const listenPulse = useRef(0)

  useFrame((state, delta) => {
    if (groupRef.current) {
      // Gentle floating animation
      groupRef.current.position.y = Math.sin(state.clock.elapsedTime * 0.8) * 0.1

      // Idle rotation
      if (!isSpeaking && !isListening) {
        idleRotation.current += delta * 0.3
        groupRef.current.rotation.y = Math.sin(idleRotation.current) * 0.2
      }

      // Speaking animation - head bob and body movement
      if (isSpeaking) {
        speakAnimation.current += delta * 8
        groupRef.current.rotation.y = Math.sin(speakAnimation.current) * 0.15
        groupRef.current.position.y += Math.sin(speakAnimation.current * 2) * 0.05
        
        // Head nod while speaking
        if (headRef.current) {
          headRef.current.rotation.x = Math.sin(speakAnimation.current * 1.5) * 0.1
        }
      }

      // Listening animation - subtle pulse and attention
      if (isListening) {
        listenPulse.current += delta * 2
        const pulse = Math.sin(listenPulse.current) * 0.05 + 1
        groupRef.current.scale.setScalar(pulse)
        
        // Slight tilt when listening
        groupRef.current.rotation.z = Math.sin(listenPulse.current * 0.5) * 0.05
      } else {
        // Return to normal scale
        groupRef.current.scale.lerp(new THREE.Vector3(1, 1, 1), delta * 5)
        groupRef.current.rotation.z = THREE.MathUtils.lerp(groupRef.current.rotation.z, 0, delta * 3)
      }
    }
  })

  // Update materials for different states
  useEffect(() => {
    const eyeMaterial = materials['Aluminum_-_Anodized_Glossy_Grey']
    
    if (isSpeaking) {
      eyeMaterial.emissive.setHex(0x8b5cf6) // Purple glow when speaking
      eyeMaterial.emissiveIntensity = 0.3
    } else if (isListening) {
      eyeMaterial.emissive.setHex(0x00d9ff) // Blue glow when listening
      eyeMaterial.emissiveIntensity = 0.2
    } else {
      eyeMaterial.emissive.setHex(0x000000) // No glow when idle
      eyeMaterial.emissiveIntensity = 0
    }
  }, [isSpeaking, isListening, materials])

  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group ref={headRef} rotation={[-3.14, 0, 0]}>
        <mesh castShadow receiveShadow geometry={nodes.Object_2.geometry} material={materials.Acetal_Resin_White_2} />
        <mesh castShadow receiveShadow geometry={nodes.Object_3.geometry} material={materials['Aluminum_-_Anodized_Glossy_Grey']} />
        <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.ABS_White} />
        <mesh castShadow receiveShadow geometry={nodes.Object_5.geometry} material={materials.Acetal_Resin_White} />
        <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials.Acetal_Resin_White} />
        <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials.Acetal_Resin_White_1} />
        <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Aluminum_-_Anodized_Rough_Grey']} />
      </group>
    </group>
  )
}

useGLTF.preload('/mini_robot.glb')
